; AddVariables.asm - Chapter 3 example.

COMMENT !
Modify the AddVariables program so it uses 64-bit variables. 
Describe the syntax errors generated by the assembler and 
what steps you took to resolve the errors.
The errors will be in regards to using 64 bit registers
!

.386
.model flat,stdcall
.stack 4096
extrn ExitProcess: proc 

.data
firstval  qword 20002000h
secondval qword 11111111h
thirdval  qword 22222222h
sum qword 0

.code
main proc
	mov	rcx,firstval				
	add	rcx,secondval		
	add rcx,thirdval
	mov sum, rcx
	invoke ExitProcess,0
main endp
end main