; AddVariables.asm - Chapter 3 example.
; Erik Vanlandingham
; CIS-361
; Last Modified 10-17-15

; Author Comment
COMMENT !
There were a lot of issues trying to get this to work with 64 bit registers. 
from the research I was able to conduct, I learned that the .386 and stack
declarations may not be necessary, and I also learned that 'r' registers
must be used.
!
COMMENT !
Modify the AddVariables program so it uses 64-bit variables. 
Describe the syntax errors generated by the assembler and 
what steps you took to resolve the errors.
The errors will be in regards to using 64 bit registers
!

.386
.model flat,stdcall
.stack 4096
extrn ExitProcess: proc 

.data
firstval  qword 20002000h
secondval qword 11111111h
thirdval  qword 22222222h
sum qword 0

.code
main proc
	mov	rcx,firstval				
	add	rcx,secondval		
	add rcx,thirdval
	mov sum, rcx
	invoke ExitProcess,0
main endp
end main