; AddVariables.asm - Chapter 3 example.

COMMENT !
Modify the AddVariables program so it uses 64-bit variables. 
Describe the syntax errors generated by the assembler and 
what steps you took to resolve the errors.
!

ExitProcess PROTO

.data
firstval  qword 20002000h
secondval qword 11111111h
thirdval  qword 22222222h
sum qword 0

.code
main proc
	???
	invoke ExitProcess
main endp
end main